import { beforeEach, describe, expect, it } from 'vitest';
import { MaxHeap, MinHeap } from '../src/heap';

// GENERATED BY Claude Sonnet 4.6

// --- Helpers ---

function makeItem(value: number) {
  return { value };
}

// ─────────────────────────────────────────────
// MaxHeap
// ─────────────────────────────────────────────

describe('MaxHeap', () => {
  let heap: MaxHeap<{ value: number }>;

  beforeEach(() => {
    heap = new MaxHeap();
  });

  describe('peek()', () => {
    it('returns null on an empty heap', () => {
      expect(heap.peek()).toBeNull();
    });

    it('returns the largest item without removing it', () => {
      heap.add(makeItem(3));
      heap.add(makeItem(10));
      heap.add(makeItem(7));
      expect(heap.peek()?.value).toBe(10);
      // still there after peek
      expect(heap.peek()?.value).toBe(10);
    });
  });

  describe('add() / remove()', () => {
    it('returns null when removing from an empty heap', () => {
      expect(heap.remove()).toBeNull();
    });

    it('removes items in descending order', () => {
      [5, 1, 9, 3, 7].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(9);
      expect(heap.remove()?.value).toBe(7);
      expect(heap.remove()?.value).toBe(5);
      expect(heap.remove()?.value).toBe(3);
      expect(heap.remove()?.value).toBe(1);
      expect(heap.remove()).toBeNull();
    });

    it('handles a single element correctly', () => {
      heap.add(makeItem(42));
      expect(heap.peek()?.value).toBe(42);
      expect(heap.remove()?.value).toBe(42);
      expect(heap.remove()).toBeNull();
    });

    it('handles duplicate values', () => {
      [4, 4, 4].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(4);
      expect(heap.remove()?.value).toBe(4);
      expect(heap.remove()?.value).toBe(4);
    });

    it('handles negative values', () => {
      [-1, -5, -3].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(-1);
      expect(heap.remove()?.value).toBe(-3);
      expect(heap.remove()?.value).toBe(-5);
    });

    it('handles mixed positive and negative values', () => {
      [-10, 0, 10, -5, 5].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(10);
      expect(heap.remove()?.value).toBe(5);
      expect(heap.remove()?.value).toBe(0);
      expect(heap.remove()?.value).toBe(-5);
      expect(heap.remove()?.value).toBe(-10);
    });
  });

  describe('extra payload fields', () => {
    it('preserves extra properties on items', () => {
      const heap2 = new MaxHeap<{ value: number; label: string }>();
      heap2.add({ value: 5, label: 'five' });
      heap2.add({ value: 1, label: 'one' });
      const top = heap2.remove();
      expect(top?.value).toBe(5);
      expect(top?.label).toBe('five');
    });
  });

  describe('large dataset', () => {
    it('sorts 1 000 random numbers in descending order', () => {
      const values = Array.from({ length: 1000 }, () => Math.random() * 10000);
      values.forEach((v) => heap.add({ value: v }));

      const sorted: number[] = [];
      let item: { value: number } | null;
      while ((item = heap.remove()) !== null) {
        sorted.push(item.value);
      }

      for (let i = 0; i < sorted.length - 1; i++) {
        expect(sorted[i]).toBeGreaterThanOrEqual(sorted[i + 1]!);
      }
    });
  });
});

// ─────────────────────────────────────────────
// MinHeap
// ─────────────────────────────────────────────

describe('MinHeap', () => {
  let heap: MinHeap<{ value: number }>;

  beforeEach(() => {
    heap = new MinHeap();
  });

  describe('peek()', () => {
    it('returns null on an empty heap', () => {
      expect(heap.peek()).toBeNull();
    });

    it('returns the smallest item without removing it', () => {
      heap.add(makeItem(3));
      heap.add(makeItem(10));
      heap.add(makeItem(7));
      expect(heap.peek()?.value).toBe(3);
      expect(heap.peek()?.value).toBe(3);
    });
  });

  describe('add() / remove()', () => {
    it('returns null when removing from an empty heap', () => {
      expect(heap.remove()).toBeNull();
    });

    it('removes items in ascending order', () => {
      [5, 1, 9, 3, 7].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(1);
      expect(heap.remove()?.value).toBe(3);
      expect(heap.remove()?.value).toBe(5);
      expect(heap.remove()?.value).toBe(7);
      expect(heap.remove()?.value).toBe(9);
      expect(heap.remove()).toBeNull();
    });

    it('handles a single element correctly', () => {
      heap.add(makeItem(42));
      expect(heap.peek()?.value).toBe(42);
      expect(heap.remove()?.value).toBe(42);
      expect(heap.remove()).toBeNull();
    });

    it('handles duplicate values', () => {
      [2, 2, 2].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(2);
      expect(heap.remove()?.value).toBe(2);
      expect(heap.remove()?.value).toBe(2);
    });

    it('handles negative values', () => {
      [-1, -5, -3].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(-5);
      expect(heap.remove()?.value).toBe(-3);
      expect(heap.remove()?.value).toBe(-1);
    });

    it('handles mixed positive and negative values', () => {
      [-10, 0, 10, -5, 5].forEach((v) => heap.add(makeItem(v)));
      expect(heap.remove()?.value).toBe(-10);
      expect(heap.remove()?.value).toBe(-5);
      expect(heap.remove()?.value).toBe(0);
      expect(heap.remove()?.value).toBe(5);
      expect(heap.remove()?.value).toBe(10);
    });
  });

  describe('extra payload fields', () => {
    it('preserves extra properties on items', () => {
      const heap2 = new MinHeap<{ value: number; label: string }>();
      heap2.add({ value: 5, label: 'five' });
      heap2.add({ value: 1, label: 'one' });
      const top = heap2.remove();
      expect(top?.value).toBe(1);
      expect(top?.label).toBe('one');
    });
  });

  describe('large dataset', () => {
    it('sorts 1 000 random numbers in ascending order', () => {
      const values = Array.from({ length: 1000 }, () => Math.random() * 10000);
      values.forEach((v) => heap.add({ value: v }));

      const sorted: number[] = [];
      let item: { value: number } | null;
      while ((item = heap.remove()) !== null) {
        sorted.push(item.value);
      }

      for (let i = 0; i < sorted.length - 1; i++) {
        expect(sorted[i]).toBeLessThanOrEqual(sorted[i + 1]!);
      }
    });
  });
});
